services:
  - type: web
    name: CHIRU DRM Uploader 
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/Chiru63019/Classplusdrm
    branch: main
    autoDeploy: false
    envVars:
      - key: token_cp
        value: eyJjb3Vyc2VJZCI6IjQ1NjY4NyIsInR1dG9ySWQiOm51bGwsIm9yZ0lkIjo0ODA2MTksImNhdGVnb3J5SWQiOm51bGx9r
        sync: true
      - key: BOT_TOKEN
        value: 
        sync: true
      - key: API_ID
        value:
        sync: false
      - key: API_HASH
        value:
        sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
